"use strict";
try{importScripts("libs/jszip.min.js");}catch(_){ }
const MIME={"image/jpeg":"jpg","image/jpg":"jpg","image/png":"png","image/gif":"gif","image/webp":"webp","image/svg+xml":"svg","image/x-icon":"ico","image/vnd.microsoft.icon":"ico","image/avif":"avif","image/bmp":"bmp"};
chrome.runtime.onMessage.addListener((m,_s,send)=>{if(!m||typeof m!=="object")return; if(m.type==="IMAGERIP_DOWNLOAD_ONE"){downloadOne(m.image).then(x=>send({ok:true,...x})).catch(e=>send({ok:false,error:msg(e)}));return true;} if(m.type==="IMAGERIP_DOWNLOAD_BATCH"){downloadBatch(Array.isArray(m.images)?m.images:[]).then(x=>send({ok:true,...x})).catch(e=>send({ok:false,error:msg(e)}));return true;}});
async function downloadOne(image){if(!image||typeof image.url!=="string"||!image.url)throw new Error("Invalid image URL");const f=norm(image.format);let name=buildName(image.url,0,f,"");try{const id=await chrome.downloads.download({url:image.url,filename:name,conflictAction:"uniquify",saveAs:false});return{downloadId:id};}catch(_){const data=await fetchBlob(image.url);const ext=inferExt(image.url,f,data.type);name=ensureExt(stripExt(name),ext);const u=URL.createObjectURL(data.blob);try{const id=await chrome.downloads.download({url:u,filename:name,conflictAction:"uniquify",saveAs:false});return{downloadId:id};}finally{setTimeout(()=>URL.revokeObjectURL(u),6e4);}}}
async function downloadBatch(images){if(!images.length)throw new Error("No images to download");if(typeof JSZip!=="function")throw new Error("JSZip unavailable");const zip=new JSZip(),used=new Set(),failed=[];let added=0;for(let i=0;i<images.length;i++){const it=images[i]||{};const url=typeof it.url==="string"?it.url:"";if(!url){failed.push({url:"",reason:"Missing URL"});continue;}try{const data=await fetchBlob(url);const ext=inferExt(url,norm(it.format),data.type);const name=unique(buildName(url,i,ext,data.type),used);zip.file(name,data.blob);added++;}catch(e){failed.push({url,reason:msg(e)});}}if(!added)throw new Error("Unable to fetch images");const zb=await zip.generateAsync({type:"blob"});const zu=URL.createObjectURL(zb);try{const id=await chrome.downloads.download({url:zu,filename:"imagerip-pro-export.zip",conflictAction:"uniquify",saveAs:true});return{downloadId:id,failed,addedCount:added,total:images.length};}finally{setTimeout(()=>URL.revokeObjectURL(zu),6e4);}}
async function fetchBlob(url){const inline=/^(data:|blob:)/i.test(url);const res=await fetch(url,inline?undefined:{credentials:"include",cache:"force-cache"});if(!res.ok)throw new Error(`HTTP ${res.status}`);const blob=await res.blob();return{blob,type:res.headers.get("content-type")||blob.type||""};}
function buildName(url,i,pref,type){const base=clean(baseName(url,i));const safe=trimDots(base)||`image-${String(i+1).padStart(3,"0")}`;return ensureExt(safe,inferExt(url,pref,type));}
function baseName(url,i){if(/^(data:|blob:)/i.test(url))return`image-${String(i+1).padStart(3,"0")}`;try{const u=new URL(url);const last=u.pathname.split("/").pop()||"";const d=dec(last);if(d)return d;}catch(_){ }return`image-${String(i+1).padStart(3,"0")}`;}
function unique(name,used){if(!used.has(name)){used.add(name);return name;}const m=name.match(/\.([a-z0-9]{2,5})$/i),ext=m?`.${m[1]}`:"",stem=ext?name.slice(0,-ext.length):name;let n=1,c=`${stem} (${n})${ext}`;while(used.has(c)){n++;c=`${stem} (${n})${ext}`;}used.add(c);return c;}
function inferExt(url,pref,type){const p=norm(pref);if(p!=="other")return p;const m=MIME[(type||"").toLowerCase()];if(m)return m;if(/^data:/i.test(url)){const d=/^data:([^;,]+)[;,]/i.exec(url);if(d&&MIME[d[1].toLowerCase()])return MIME[d[1].toLowerCase()];}try{const e=(new URL(url)).pathname.match(/\.([a-z0-9]{2,5})$/i);if(e)return norm(e[1]);}catch(_){ }return"img";}
function norm(f){const v=String(f||"").toLowerCase();if(v==="jpeg")return"jpg";return["jpg","png","gif","webp","svg","ico","avif","bmp"].includes(v)?v:"other";}
function ensureExt(b,e){if(/\.[a-z0-9]{2,5}$/i.test(b))return b;return`${b}.${e&&e!=="other"?e:"img"}`;}
function stripExt(n){return n.replace(/\.[a-z0-9]{2,5}$/i,"");}
function clean(n){return String(n||"").split("?")[0].split("#")[0].replace(/[<>:"/\\|?*\u0000-\u001F]/g,"_").replace(/\s+/g," ").trim();}
function trimDots(n){return String(n||"").replace(/\.+$/g,"").trim();}
function dec(v){try{return decodeURIComponent(v);}catch(_){return v;}}
function msg(e){if(!e)return"Unknown error";if(typeof e==="string")return e;return e.message||String(e);}


