(()=>{const TTL=5e3,M={"image/jpeg":"jpg","image/jpg":"jpg","image/png":"png","image/gif":"gif","image/webp":"webp","image/svg+xml":"svg","image/x-icon":"ico","image/vnd.microsoft.icon":"ico","image/avif":"avif","image/bmp":"bmp"};const S={cache:[],last:0,p:null};
chrome.runtime.onMessage.addListener((m,_s,send)=>{if(!m||typeof m!=="object")return; if(m.type==="IMAGERIP_SCAN"){run(!!m.force).then(send).catch(e=>send({ok:false,error:msg(e),images:[]}));return true;} if(m.type==="IMAGERIP_GET_CACHE"){send({ok:true,images:S.cache});return false;}});
setTimeout(()=>{run(false).catch(()=>{});},120);
async function run(force){const now=Date.now();if(!force&&S.p)return S.p;if(!force&&S.cache.length&&now-S.last<TTL)return{ok:true,images:S.cache};S.p=scan().then(images=>{S.cache=images;S.last=Date.now();return{ok:true,images};}).catch(e=>({ok:false,error:msg(e),images:[]})).finally(()=>{S.p=null;});return S.p;}
async function scan(){const map=new Map(),seen=new WeakSet();await scanRoot(document,map,location.href,seen);const out=Array.from(map.values());await resolveBlob(out);return out;}
async function scanRoot(root,map,base,seen){if(!root||seen.has(root))return;seen.add(root);if(root instanceof Document)meta(root,map,base);if(!root.querySelectorAll)return;const els=Array.from(root.querySelectorAll("*")),pending=[];await idle(els,el=>fromEl(el,map,base,pending,seen));if(pending.length)await Promise.allSettled(pending);}
function meta(doc,map,base){const ms=['meta[property="og:image"]','meta[property="og:image:url"]','meta[name="twitter:image"]','meta[name="twitter:image:src"]','meta[property="twitter:image"]','meta[property="twitter:image:src"]'];for(const n of doc.querySelectorAll(ms.join(","))){add(map,{url:n.getAttribute("content"),base,type:"meta",width:0,height:0,alt:""});}for(const n of doc.querySelectorAll('link[rel*="icon"],link[rel*="apple-touch-icon"]')){add(map,{url:n.getAttribute("href"),base,type:"icon",width:0,height:0,alt:""});}for(const n of doc.querySelectorAll('script[type="application/ld+json"]')){const t=n.textContent||"";if(!t.trim())continue;try{const j=JSON.parse(t);walkJson(j,u=>add(map,{url:u,base,type:"json-ld",width:0,height:0,alt:""}));}catch(_){}}}
function walkJson(v,push){const st=[v];while(st.length){const cur=st.pop();if(!cur)continue;if(Array.isArray(cur)){for(let i=cur.length-1;i>=0;i--)st.push(cur[i]);continue;}if(typeof cur!=="object")continue;for(const [k,val] of Object.entries(cur)){if(k.toLowerCase().includes("image"))extJson(val,push);if(val&&typeof val==="object")st.push(val);}}}
function extJson(v,push){if(!v)return;if(typeof v==="string"){push(v);return;}if(Array.isArray(v)){for(const x of v)extJson(x,push);return;}if(typeof v==="object"){if(typeof v.url==="string")push(v.url);if(typeof v.contentUrl==="string")push(v.contentUrl);if(typeof v["@id"]==="string"&&/^(https?:|data:|blob:|\/)/i.test(v["@id"]))push(v["@id"]);}}
function fromEl(el,map,base,pending,seen){if(!el||el.nodeType!==1)return;if(el.shadowRoot)pending.push(scanRoot(el.shadowRoot,map,base,seen));if(el.tagName==="IFRAME")pending.push(frame(el,map,seen));fromCss(el,map,base);const t=el.tagName.toLowerCase();if(t==="img"){fromImg(el,map,base);return;}if(t==="source"){fromSource(el,map,base);return;}if(t==="svg"){fromSvg(el,map,base);return;}if(t==="canvas")fromCanvas(el,map,base);}
function fromImg(img,map,base){const d=dims(img),alt=img.getAttribute("alt")||img.getAttribute("aria-label")||"",src=new Set();if(img.currentSrc)src.add(img.currentSrc);for(const a of ["src","data-src","data-lazy-src","data-original","data-image","data-thumb","data-lazy"]){const v=img.getAttribute(a);if(v)src.add(v);}for(const a of ["srcset","data-srcset"]){const v=img.getAttribute(a);if(!v)continue;for(const u of parseSrcset(v,base))src.add(u);}for(const u of src)add(map,{url:u,base,type:"img",width:d.width,height:d.height,alt});}
function fromSource(s,map,base){const ss=s.getAttribute("srcset")||s.getAttribute("data-srcset");if(!ss)return;for(const u of parseSrcset(ss,base))add(map,{url:u,base,type:"picture-source",width:0,height:0,alt:""});}
function fromSvg(svg,map,base){try{const x=new XMLSerializer().serializeToString(svg);if(!x||x.length<6)return;const d=svgDims(svg);add(map,{url:`data:image/svg+xml;charset=utf-8,${encodeURIComponent(x)}`,base,type:"inline-svg",width:d.width,height:d.height,alt:"",format:"svg"});}catch(_){}}
function fromCanvas(c,map,base){try{add(map,{url:c.toDataURL("image/png"),base,type:"canvas",width:Number(c.width)||0,height:Number(c.height)||0,alt:"",format:"png"});}catch(_){}}
function fromCss(el,map,base){const d=dims(el),vals=[];if(el.style){vals.push(el.style.backgroundImage||"");vals.push(el.style.background||"");}try{const cs=getComputedStyle(el);vals.push(cs.backgroundImage||"");vals.push(cs.listStyleImage||"");}catch(_){ }for(const v of vals){if(!v||v==="none")continue;for(const u of cssUrls(v,base))add(map,{url:u,base,type:"css-background",width:d.width,height:d.height,alt:""});}}
async function frame(ifr,map,seen){try{const doc=ifr.contentDocument;if(!doc||!doc.documentElement)return;const b=doc.location?doc.location.href:ifr.src||location.href;await scanRoot(doc,map,b,seen);}catch(_){ }}
function add(map,c){const abs=absUrl(c.url,c.base||location.href);if(!abs)return;const k=dkey(abs),w=num(c.width),h=num(c.height),f=norm(c.format||fmt(abs,c.contentType||"")),t=String(c.type||"unknown"),a=String(c.alt||""),warn=String(c.warning||"");if(map.has(k)){const e=map.get(k);if(e.type.indexOf(t)===-1)e.type=`${e.type},${t}`;e.width=Math.max(e.width,w);e.height=Math.max(e.height,h);if(!e.alt&&a)e.alt=a;if(e.format==="other"&&f!=="other")e.format=f;if(!e.warning&&warn)e.warning=warn;return;}map.set(k,{url:abs,type:t,width:w,height:h,alt:a,format:f,warning:warn});}
function dims(el){return{width:num(el.naturalWidth||el.videoWidth||el.clientWidth||el.width),height:num(el.naturalHeight||el.videoHeight||el.clientHeight||el.height)}}
function svgDims(svg){const w=parseFloat(svg.getAttribute("width")||"0"),h=parseFloat(svg.getAttribute("height")||"0");if(w>0&&h>0)return{width:Math.round(w),height:Math.round(h)};const vb=(svg.getAttribute("viewBox")||"").trim().split(/\s+/);if(vb.length===4)return{width:num(parseFloat(vb[2])),height:num(parseFloat(vb[3]))};return dims(svg)}
function num(v){const n=Number(v);return Number.isFinite(n)&&n>0?Math.round(n):0}
function absUrl(u,b){if(!u)return"";const t=String(u).trim();if(!t||t==="#"||/^javascript:/i.test(t))return"";try{return new URL(t,b).href}catch(_){return""}}
function dkey(url){if(/^(data:|blob:)/i.test(url))return url;try{const u=new URL(url,location.href);u.search="";u.hash="";return u.href}catch(_){return url}}
function fmt(url,type){const m=M[String(type||"").toLowerCase()];if(m)return m;const d=/^data:([^;,]+)[;,]/i.exec(url);if(d)return M[d[1].toLowerCase()]||"other";const e=url.match(/\.([a-z0-9]{2,5})(?:$|[?#])/i);return e?norm(e[1]):"other"}
function norm(f){const v=String(f||"").toLowerCase();if(v==="jpeg")return"jpg";return["jpg","png","gif","webp","svg","ico","avif","bmp"].includes(v)?v:"other"}
function parseSrcset(s,b){if(!s)return[];return s.split(",").map(p=>p.trim().split(/\s+/)[0]).map(t=>t.replace(/^['"]|['"]$/g,"")) .map(v=>absUrl(v,b)).filter(Boolean)}
function cssUrls(v,b){const out=[],re=/url\((['"]?)(.*?)\1\)/gi;let m;while((m=re.exec(v))!==null){const u=absUrl(m[2],b);if(u)out.push(u);}return out}
function idle(els,fn){return new Promise(res=>{let i=0;const byIdle=d=>{while(i<els.length&&d.timeRemaining()>3){fn(els[i]);i++;}if(i<els.length)requestIdleCallback(byIdle,{timeout:150});else res();};const byTimeout=()=>{const s=Date.now();while(i<els.length&&Date.now()-s<14){fn(els[i]);i++;}if(i<els.length)setTimeout(byTimeout,0);else res();};if(typeof requestIdleCallback==="function")requestIdleCallback(byIdle,{timeout:150});else byTimeout();})}
async function resolveBlob(list){const blobs=list.filter(i=>typeof i.url==="string"&&i.url.startsWith("blob:"));if(!blobs.length)return;await Promise.allSettled(blobs.map(async i=>{try{const r=await fetch(i.url);if(!r.ok)throw new Error(`HTTP ${r.status}`);const b=await r.blob();i.url=await blobToData(b);if(i.format==="other")i.format=norm(fmt("",b.type));}catch(_){i.warning=i.warning||"Blob URL unavailable";}}))}
function blobToData(b){return new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(String(r.result||""));r.onerror=()=>rej(r.error||new Error("Failed to read blob"));r.readAsDataURL(b);})}
function msg(e){if(!e)return"Unknown error";if(typeof e==="string")return e;return e.message||String(e)}
})();
